// import { MediosTransporte } from '@entities';

// export const MEDIOSTRANSPORTE: MediosTransporte[] = [
//   {
//     code: 11,
//     name: 'BICICLETA',
//     ServiceCode: 1000,
//     type: 'BICYCLING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
//   {
//     code: 12,
//     name: 'MOTO',
//     ServiceCode: 1000,
//     type: 'DRIVING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
//   {
//     code: 13,
//     name: 'VEHICULO PARTICULAR',
//     ServiceCode: 2000,
//     type: 'DRIVING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
//   {
//     code: 14,
//     name: 'CARRO PLACA BLANCA',
//     ServiceCode: 2000,
//     type: 'DRIVING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
//   {
//     code: 15,
//     name: 'CAMIONETA',
//     ServiceCode: 3000,
//     type: 'DRIVING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
//   {
//     code: 16,
//     name: 'FURGON',
//     ServiceCode: 3000,
//     type: 'DRIVING',
//     tarifa_ini: 5900,
//     tarife_sec: 4000,
//     tarifa_mts: 90,
//     distancia_ini: 4000,
//     recargo_noc: 1000,
//     recargo_fest: 1000,
//     image: '',
//     weightLimit: 7,
//     sizeLimit: '40 x 40 x 40 cm',
//     distanceLimit: 10,
//   },
// ];
