//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPPAC.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIPPAC.Entities.Resources.EntityMessages", typeof(EntityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo dirección es obligatorio.
        /// </summary>
        internal static string Address_Required {
            get {
                return ResourceManager.GetString("Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario agent es requerido.
        /// </summary>
        internal static string AgentUser_Required {
            get {
                return ResourceManager.GetString("AgentUser_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos es Requeridos.
        /// </summary>
        internal static string Apellidos_Required {
            get {
                return ResourceManager.GetString("Apellidos_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario caller es requerido.
        /// </summary>
        internal static string CallUser_Required {
            get {
                return ResourceManager.GetString("CallUser_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Requerida.
        /// </summary>
        internal static string Category_Required {
            get {
                return ResourceManager.GetString("Category_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono no es valido.
        /// </summary>
        internal static string CellPhon_Number {
            get {
                return ResourceManager.GetString("CellPhon_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar por lo menos un telefono de contacto.
        /// </summary>
        internal static string Cellphones_Required {
            get {
                return ResourceManager.GetString("Cellphones_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo ciudad es obligatorio.
        /// </summary>
        internal static string City_Required {
            get {
                return ResourceManager.GetString("City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del cliente es requerido.
        /// </summary>
        internal static string CliId_Required {
            get {
                return ResourceManager.GetString("CliId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de contacto es obligatorio.
        /// </summary>
        internal static string ContactName_Required {
            get {
                return ResourceManager.GetString("ContactName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo departamento es obligatorio.
        /// </summary>
        internal static string Dept_Required {
            get {
                return ResourceManager.GetString("Dept_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del dispositivo es requirido.
        /// </summary>
        internal static string Device_Required {
            get {
                return ResourceManager.GetString("Device_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion es Requerido.
        /// </summary>
        internal static string Direccion_Required {
            get {
                return ResourceManager.GetString("Direccion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email no es valido.
        /// </summary>
        internal static string Email_FormatEmail {
            get {
                return ResourceManager.GetString("Email_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email es requerido.
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        internal static string EmailAddress_FormatEmail {
            get {
                return ResourceManager.GetString("EmailAddress_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailAddress_Required {
            get {
                return ResourceManager.GetString("EmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin requerida.
        /// </summary>
        internal static string EndDate_Required {
            get {
                return ResourceManager.GetString("EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha final es requerida.
        /// </summary>
        internal static string FechaFin_Required {
            get {
                return ResourceManager.GetString("FechaFin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha inicial es requerida.
        /// </summary>
        internal static string FechaIni_Required {
            get {
                return ResourceManager.GetString("FechaIni_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is required.
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo genero es obligatorio.
        /// </summary>
        internal static string Genre_Required {
            get {
                return ResourceManager.GetString("Genre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo identificación es obligatorio.
        /// </summary>
        internal static string Id_Required {
            get {
                return ResourceManager.GetString("Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Parametro Requerido.
        /// </summary>
        internal static string IdParameter__Required {
            get {
                return ResourceManager.GetString("IdParameter__Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is required.
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres es Requerido.
        /// </summary>
        internal static string Nombres_Required {
            get {
                return ResourceManager.GetString("Nombres_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de solicitud de subsidio es requerido.
        /// </summary>
        internal static string NoSubsidyRequest_Required {
            get {
                return ResourceManager.GetString("NoSubsidyRequest_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo número Sap es requerido.
        /// </summary>
        internal static string NumberSapSubsidy_Request {
            get {
                return ResourceManager.GetString("NumberSapSubsidy_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de la cuenta es requerido.
        /// </summary>
        internal static string NumCuenta_Required {
            get {
                return ResourceManager.GetString("NumCuenta_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de la cuenta Destino es requerido.
        /// </summary>
        internal static string NumCuentaDestino_Required {
            get {
                return ResourceManager.GetString("NumCuentaDestino_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo observaciones es obligatorio.
        /// </summary>
        internal static string ObservationsSubsidy_Request {
            get {
                return ResourceManager.GetString("ObservationsSubsidy_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token de acceso al la llamada es obligatorio.
        /// </summary>
        internal static string OpenTokAccessToken_Required {
            get {
                return ResourceManager.GetString("OpenTokAccessToken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Session Id es requerido.
        /// </summary>
        internal static string OpenTokSessionId_Required {
            get {
                return ResourceManager.GetString("OpenTokSessionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should fear more than 4 characters.
        /// </summary>
        internal static string Password_LengthPassword {
            get {
                return ResourceManager.GetString("Password_LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo excede la cantidad de caracteres permitida.
        /// </summary>
        internal static string PDIField_Length {
            get {
                return ResourceManager.GetString("PDIField_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos del PDI son requeridos.
        /// </summary>
        internal static string PDIField_Required {
            get {
                return ResourceManager.GetString("PDIField_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo del funcionario es obligatorio.
        /// </summary>
        internal static string Position_Required {
            get {
                return ResourceManager.GetString("Position_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario del funcionario es requerido.
        /// </summary>
        internal static string Reviewer_Required {
            get {
                return ResourceManager.GetString("Reviewer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        internal static string Role_Required {
            get {
                return ResourceManager.GetString("Role_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El saldo de la cuenta es requerido.
        /// </summary>
        internal static string Saldo_Required {
            get {
                return ResourceManager.GetString("Saldo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El puntaje de la llamada es requerido.
        /// </summary>
        internal static string Score_Required {
            get {
                return ResourceManager.GetString("Score_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El session id es requerido.
        /// </summary>
        internal static string SessionId_Required {
            get {
                return ResourceManager.GetString("SessionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo razón social de la empresa es obligatorio.
        /// </summary>
        internal static string SocialReason_Required {
            get {
                return ResourceManager.GetString("SocialReason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio requerida.
        /// </summary>
        internal static string StartDate_Required {
            get {
                return ResourceManager.GetString("StartDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado del funcionario es obligatorio.
        /// </summary>
        internal static string State_Required {
            get {
                return ResourceManager.GetString("State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada es requerido.
        /// </summary>
        internal static string StateCall_Required {
            get {
                return ResourceManager.GetString("StateCall_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada no es valido.
        /// </summary>
        internal static string StateCall_Valid {
            get {
                return ResourceManager.GetString("StateCall_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la solicitud de subsidio es requerido.
        /// </summary>
        internal static string StateSubsid_Required {
            get {
                return ResourceManager.GetString("StateSubsid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono es Requerido.
        /// </summary>
        internal static string Telefono_Required {
            get {
                return ResourceManager.GetString("Telefono_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de cuenta es requerido.
        /// </summary>
        internal static string TipoCuenta_Required {
            get {
                return ResourceManager.GetString("TipoCuenta_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token id es requerido.
        /// </summary>
        internal static string TokenId_Required {
            get {
                return ResourceManager.GetString("TokenId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de identificación.
        /// </summary>
        internal static string TypeId_Required {
            get {
                return ResourceManager.GetString("TypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de Identificación es Obligatorio.
        /// </summary>
        internal static string UPId_Required {
            get {
                return ResourceManager.GetString("UPId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de Identificación es Obligatorio.
        /// </summary>
        internal static string UPTypeId_Required {
            get {
                return ResourceManager.GetString("UPTypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario es obligatorio y corresponde al noDoc_CodTypeDoc.
        /// </summary>
        internal static string User_Required {
            get {
                return ResourceManager.GetString("User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe definir el tipo de usuario a registrar.
        /// </summary>
        internal static string UserType_Required {
            get {
                return ResourceManager.GetString("UserType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de la consignacion es requerido.
        /// </summary>
        internal static string ValorConsignacion_Required {
            get {
                return ResourceManager.GetString("ValorConsignacion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor parametro rerquerido.
        /// </summary>
        internal static string ValueParameter_Required {
            get {
                return ResourceManager.GetString("ValueParameter_Required", resourceCulture);
            }
        }
    }
}
