//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPPAC.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametersApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametersApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIPPAC.Utils.Resources.ParametersApp", typeof(ParametersApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///		&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;/head&gt;	
        ///  &lt;body&gt;
        ///&lt;table&gt;
        ///&lt;tbody&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///
        ///  &lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;
        /// {0} {1} {2}: Su solicitud fue cargada exitosamente, una vez revisada la documentación y el formulario único de postulación, le estaremos informando por éste medio si fue aceptada o rechazada la solicitud
        ///  &lt;/p&gt;
        ///  
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;  
        ///  &lt;/body&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodiMailRequestSubsidy {
            get {
                return ResourceManager.GetString("BodiMailRequestSubsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///		&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;/head&gt;	
        ///  &lt;body&gt;
        ///&lt;table&gt;
        ///&lt;tbody&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///
        ///  &lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;
        ///  Estimad{0}. {1} {2}, nos da much&amp;iacute;simo gusto escribirte el d&amp;iacute;a hoy. 
        ///  &lt;br /&gt;&lt;br /&gt;
        ///  Recibe un Cordial Saludo:
        ///  &lt;br /&gt;&lt;br /&gt;
        ///  Tu solicitud de subsidio {3}, acaba de pasar al estado {4}.
        ///  &lt;br /&gt;&lt;br /&gt;
        ///  Observaciones de la gestión: {5}
        ///  &lt;/p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailNotificationSubsidy {
            get {
                return ResourceManager.GetString("BodyMailNotificationSubsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td &gt;{0} {1}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td &gt;
        ///Por favor ingrese al siguiente link para completar el proceso de cambio de clave. &lt;br/&gt; {2}.
        ///&lt;/span&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        public static string BodyMailPass {
            get {
                return ResourceManager.GetString("BodyMailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;h1 style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;Correo PDI&lt;/h1&gt;
        ///	&lt;h2 style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;{0} {1}&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div&gt;
        ///  &lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;
        ///    Buen d&amp;iacute;a: En el presente correo se adjunta el documento PDI en formato PDF.
        ///  &lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string BodyMailPDI {
            get {
                return ResourceManager.GetString("BodyMailPDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;text-align: center;&quot;&gt;
        ///&lt;p style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;&lt;/p&gt;
        ///&lt;span style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;{0} {1}&lt;/span&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;Buen d&amp;iacute;a: has actualizado tus datos con exito.&lt;/p&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        public static string BodyMailUpate {
            get {
                return ResourceManager.GetString("BodyMailUpate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;text-align: center;&quot;&gt;
        ///&lt;p style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;Bienvenido&lt;/p&gt;
        ///&lt;span style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;{0}&lt;/span&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;Buen d&amp;iacute;a: Agradecemos por haberte registrado en la Agencia de Empleo Colsubsidio. Recuerda ingresar a &lt;a href=&quot;www. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailWelcomeCompany {
            get {
                return ResourceManager.GetString("BodyMailWelcomeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///		&lt;title&gt;Welcome-Mail&lt;/title&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;/head&gt;	
        ///  &lt;body&gt;
        ///&lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;text-align: center;&quot;&gt;
        ///&lt;p style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;Bienvenido&lt;/p&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;Estimad{0}. {1} {2}, nos da much&amp;iacute;simo gusto escribirte el d&amp;iacute;a hoy. &lt;br /&gt;&lt;br /&gt; Recibe un Cordial Salud [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailWelcomePerson {
            get {
                return ResourceManager.GetString("BodyMailWelcomePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&quot;0&quot; style=&quot;width: 900px&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr style=&quot;background:#00425f&quot;&gt;
        ///			&lt;td colspan=&quot;7&quot; style=&quot;text-align: center&quot;&gt;&lt;img src=&quot;https://colsagenciavirtualprodweb.azurewebsites.net/assets/images/images/colsubsidio_logo.png&quot; alt=&quot;&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr style=&quot;background:#00597c; padding: 10px;&quot;&gt;
        ///			&lt;td colspan=&quot;7&quot; style=&quot;text-align: left&quot;&gt;&lt;img src=&quot;https://colsagenciavirtualprodweb.azurewebsites.net/assets/images/images/agencia_de_empleo_logo.png&quot; alt=&quot;&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td colspan= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentPDIPdf {
            get {
                return ResourceManager.GetString("ContentPDIPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colsubsidioprueba@gmail.com.
        /// </summary>
        public static string EmailAddressFrom {
            get {
                return ResourceManager.GetString("EmailAddressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColsubsidioApp.
        /// </summary>
        public static string KeyCrypt {
            get {
                return ResourceManager.GetString("KeyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia Virtual de empleo.
        /// </summary>
        public static string NameEmail {
            get {
                return ResourceManager.GetString("NameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insight123resultxyz.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e84ad660c4721ae0e84ad660c4721ae0.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar Contraseña Usuario Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectPass {
            get {
                return ResourceManager.GetString("SubJectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento PDI Agencia Virtual de Empleo.
        /// </summary>
        public static string SubjectPDI {
            get {
                return ResourceManager.GetString("SubjectPDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidio Colsubsidio.
        /// </summary>
        public static string SubjectSubsidyRequest {
            get {
                return ResourceManager.GetString("SubjectSubsidyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización Exitosa Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectUpdate {
            get {
                return ResourceManager.GetString("SubJectUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectWelcome {
            get {
                return ResourceManager.GetString("SubJectWelcome", resourceCulture);
            }
        }
    }
}
