//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPPAC.Utils.ResponseMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIPPAC.Utils.ResponseMessages.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay agentes disponibles.
        /// </summary>
        internal static string AgentNotAvailable {
            get {
                return ResourceManager.GetString("AgentNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra ningun agente .
        /// </summary>
        internal static string AgentNotFound {
            get {
                return ResourceManager.GetString("AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en los siguientes campos: {0}{1}.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente creado correctamente..
        /// </summary>
        internal static string ClientCreatedOk {
            get {
                return ResourceManager.GetString("ClientCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el cliente consultado.
        /// </summary>
        internal static string ClienteNoExiste {
            get {
                return ResourceManager.GetString("ClienteNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta consultada.
        /// </summary>
        internal static string CuentaNoExiste {
            get {
                return ResourceManager.GetString("CuentaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo no se encuentra registrado.
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Correo no es valido.
        /// </summary>
        internal static string EmailAddress_FormatEmail {
            get {
                return ResourceManager.GetString("EmailAddress_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha presentado un error en el Sistema, intente mas tardes.
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error request..
        /// </summary>
        internal static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error enviando el correo.
        /// </summary>
        internal static string ErrorSendMail {
            get {
                return ResourceManager.GetString("ErrorSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de recordación de contraseña expiro solicite uno nuevo.
        /// </summary>
        internal static string ExpiredtokenRPassword {
            get {
                return ResourceManager.GetString("ExpiredtokenRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A exceeded the number of failed attempts..
        /// </summary>
        internal static string FailedAttempts {
            get {
                return ResourceManager.GetString("FailedAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay solicitudes de subsidio activas.
        /// </summary>
        internal static string HaveNotSubsidyRequest {
            get {
                return ResourceManager.GetString("HaveNotSubsidyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Incorrecta.
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación fallida, por favor intenta mas tarde..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de recordación de contraseña no es valido.
        /// </summary>
        internal static string InvalidtokenRPassword {
            get {
                return ResourceManager.GetString("InvalidtokenRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id del dispositivo no se encuentra autenticado.
        /// </summary>
        internal static string IsNotAuthenticate {
            get {
                return ResourceManager.GetString("IsNotAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no esta registrado en nuestra base de datos.
        /// </summary>
        internal static string IsNotRegisterInAz {
            get {
                return ResourceManager.GetString("IsNotRegisterInAz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación fallida.
        /// </summary>
        internal static string IsNotRegisterInLdap {
            get {
                return ResourceManager.GetString("IsNotRegisterInLdap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No realizaste alguna actualización en nuestro sistema.
        /// </summary>
        internal static string NotUpdate {
            get {
                return ResourceManager.GetString("NotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro no registrado..
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo insuficiente en la cuenta..
        /// </summary>
        internal static string SaldoInsuficiente {
            get {
                return ResourceManager.GetString("SaldoInsuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado exitoso..
        /// </summary>
        internal static string SavePDI {
            get {
                return ResourceManager.GetString("SavePDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío y guardado exitoso..
        /// </summary>
        internal static string SendAndSavePDI {
            get {
                return ResourceManager.GetString("SendAndSavePDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inesperado en un servicio externo, por favor intentar mas tarde..
        /// </summary>
        internal static string ServiceExternalError {
            get {
                return ResourceManager.GetString("ServiceExternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El subsidio se encuentra en proceso.
        /// </summary>
        internal static string SubsidyInProcess {
            get {
                return ResourceManager.GetString("SubsidyInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation done correctly..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token y el dispositivo no corresponden..
        /// </summary>
        internal static string TokenAndDeviceNotFound {
            get {
                return ResourceManager.GetString("TokenAndDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro no exitoso, el usuario ya existe.
        /// </summary>
        internal static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario existe como funcionario. Para poder registrarse como Persona debe solicitar que deshabiliten el usuario de funcionario..
        /// </summary>
        internal static string UserAlredyExistF {
            get {
                return ResourceManager.GetString("UserAlredyExistF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se bloqueo debido a que excedió la cantidad de intentos..
        /// </summary>
        internal static string UserBlock {
            get {
                return ResourceManager.GetString("UserBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede autenticar, El usuario está en llamada..
        /// </summary>
        internal static string UserCalling {
            get {
                return ResourceManager.GetString("UserCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        internal static string UserCreatedOk {
            get {
                return ResourceManager.GetString("UserCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se encuentra deshabilitado.
        /// </summary>
        internal static string UserDesable {
            get {
                return ResourceManager.GetString("UserDesable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario No tiene Llamadas Registradas.
        /// </summary>
        internal static string UserDoNotHaveCalls {
            get {
                return ResourceManager.GetString("UserDoNotHaveCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no tiene solicitudes de subsidio..
        /// </summary>
        internal static string UserHaveNotSubsidyRequest {
            get {
                return ResourceManager.GetString("UserHaveNotSubsidyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado..
        /// </summary>
        internal static string UserIsNotVip {
            get {
                return ResourceManager.GetString("UserIsNotVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o correo electrónico no proporcionado en la petición..
        /// </summary>
        internal static string UserOrEmailNotRepuest {
            get {
                return ResourceManager.GetString("UserOrEmailNotRepuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene PDI asociado.
        /// </summary>
        internal static string UserWithoutPDI {
            get {
                return ResourceManager.GetString("UserWithoutPDI", resourceCulture);
            }
        }
    }
}
